// example of custom API
import groovy.json.JsonSlurperClassic 

@NonCPS
def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

def repo = "ewalasagas/docker-demo"

def token = httpRequest authentication: 'bitbucket-oauth', 
            contentType: 'APPLICATION_FORM', 
            httpMode: 'POST', 
            requestBody: 'grant_type=client_credentials', 
            url: 'https://bitbucket.org/Schveet_arse/oauth2/access_token'

nse = httpRequest acceptType: "APPLICATION_JSON", 
          contentType: "APPLICATION_JSON",
          customHeaders: [[name: 'Authorization', value: token]],
          url: server+port+"/exams"+testID,respo
          validResponseCodes: '200:404'

def accessToken = jsonParse(token.content).access_token
def pr = httpRequest acceptType: "APPLICATION_JSON", 
          contentType: "APPLICATION_JSON",
          customHeaders: [[name: 'Authorization', value: token]], 
          url: "https://api.bitbucket.org/2.0/repositories/${repo}/pullrequests",
          validResponseCodes: '200:404'

for (p in jsonParse(pr.content).values) { 
    println(p.source.branch.name)
}